name: Test and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      droplets_pricing:
        description: Droplets JSON pricing data
        required: false
        default: ''
      kubernetes_pricing:
        description: Kubernetes JSON pricing data
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}

    - name: Get pricing data for Droplets
      env:
        TYPE: droplets
        DATA: ${{ github.event.inputs.droplets_pricing }}
      run: ./ci/get-pricing-data.sh

    - name: Get pricing data for Kubernetes
      env:
        TYPE: kubernetes
        DATA: ${{ github.event.inputs.kubernetes_pricing }}
      run: ./ci/get-pricing-data.sh

    - name: npm ci, test, and build
      run: |
        cat build/droplets.json
        cat build/kubernetes.json
        npm ci
        npm test
        npm run build
        exit 1
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Deploy master to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.DEV_GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
        SINGLE_COMMIT: true
